version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: php-docker
    ports:
      - 8085:80
    volumes:
      - .:/srv/app
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: treehicks
      DB_USERNAME: root
      DB_PASSWORD: e
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: treehicks
      MYSQL_USER: root
#      MYSQL_PASSWORD: e
      MYSQL_ROOT_PASSWORD: e
    volumes:
      - my-datavolume:/var/lib/mysql



volumes:
  my-datavolume: